### ISSUE TITLE
Don't create "mods\nicephore" folder if screenshot optimization is off.

### ISSUE THREAD

**Issue by Xrey274** [LotuxPunk/Nicephore#11]
I don't use the screenshot optimization feature. Something that bothers me is that the references folder is created every time you start Minecraft, regardless of optimizations being turned off. Perhaps you should check in the config file if screenshot optimizations are off, and if they are not don't create the folder.

**Comment by PaintNinja** [comment]
Thanks for the suggestion! Not sure how we overlooked that...

I assume it's because we expected everyone to at least use the PNG optimisation, even if they just turn down the effort amount to the minimum for maximum speed. Even if filesizes aren't much different on the fastest speed optimisation mode, load times when sharing over the Internet are significantly faster, especially if you don't have crazy fast Internet and it's a 4k screenshot.

We'll look into implementing your suggestion in the future.

**Comment by LotuxPunk** [comment]
> I don't use the screenshot optimization feature. Something that bothers me is that the references folder is created every time you start Minecraft, regardless of optimizations being turned off. Perhaps you should check in the config file if screenshot optimizations are off, and if they are not don't create the folder.

Hey ! I have a question about that one. Is this folder empty when the optimization is on `false` ?

So, the mod is creating it, but remain empty after the loading ?

**Comment by LotuxPunk** [comment]
@PaintNinja FYI, I remove the `enhancement` label because that's an unintended behavior, this should'nt happen, I'm checking the config on the InitThread, somehow the config doesn't care about the config.toml

https://github.com/LotuxPunk/Nicephore/blob/dbe72af14a90d6a9a11ad8b95f289ce53dcac6cb/src/main/java/com/vandendaelen/nicephore/thread/InitThread.java#L30
